spring.application.name=demo

#driver-class-nameは今のspring bootではURLから自動判断してくれる
spring.datasource.url=jdbc:mysql://localhost:3306/baitodata
spring.datasource.username=Tarak
spring.datasource.password=Taraknet

#JPA/Hibernateの設定
spring.jpa.hibernate.ddl-auto=update
# 実行されたSQLをコンソールに表示する（勉強・デバッグに最適！）
spring.jpa.show-sql=true
# SQLを読みやすくフォーマットして表示する
spring.jpa.properties.hibernate.format_sql=true
# ログやデータのやり取りをUTF-8で統一します
spring.servlet.encoding.force=true
spring.servlet.encoding.charset=UTF-8

# 4. フロントエンド(React)との連携用
# Reactが3000番ポートで動くことが多いので、重複を避けるために一応記載
server.port=8080
#ターミナルでリクエストURLとステータスの表示
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.stdout=true
